server:
  port: ${CONTAINER_PORT:8080}
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    redis:
      host: ${CACHE_HOST:localhost}
      port: ${CACHE_PORT:6379}
      timeout: 1s
  cache:
    type: redis
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    user: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:postgres}
  kafka:
    bootstrap-servers: my-kafka.kafka.svc.cluster.local:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
    consumer:
      group-id: my-group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      listener:
        missing-topics-fatal: false
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        ssl:
          trust: "smtp.gmail.com"
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
resilience4j.ratelimiter:
  instances:
    register:
      limitForPeriod: 5
      limit-refresh-period: 5m
      timeoutDuration: 0s
      writable-stack-trace-enabled: false
    login:
      limitForPeriod: 7
      limit-refresh-period: 6m
      timeoutDuration: 0s
      writable-stack-trace-enabled: false
    activate-user:
      limitForPeriod: 3
      limit-refresh-period: 5m
      timeoutDuration: 0s
      writable-stack-trace-enabled: false
    refresh:
      limitForPeriod: 4
      limit-refresh-period: 5m
      timeoutDuration: 0s
      writable-stack-trace-enabled: false
    send-activation-code:
      limitForPeriod: 1
      limit-refresh-period: 4m
      timeoutDuration: 0s
      writable-stack-trace-enabled: false

app:
  auth:
    encryption-key: ${ENCRYPTION_AUTH_KEY}
  kafka:
    topics:
      subscription-purchases: subscription-purchases
      confirmed-subscriptions: confirmed-subscription-purchases