services:
  database:
    container_name: database
    image: postgres:18-alpine
    restart: on-failure:3
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - POSTGRES_DB=postgres
    ports:
      - '5433:5432'
    volumes:
      - pg-data:/var/lib/postgresql/18/docker

  cache:
    container_name: cache
    image: redis:7-alpine
    restart: on-failure:3
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'

  app:
    container_name: gymentry-app
    image: gymentry:latest
    restart: on-failure:2
    env_file:
      - .env
    ports:
      - '8080:8080'

volumes:
  pg-data:
  redis-data: