services:
  database:
    container_name: database
    image: postgres:18-alpine
    restart: on-failure:3
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - POSTGRES_DB=postgres
    ports:
      - '5433:5432'
    volumes:
      - pg-data:/var/lib/postgresql/18/docker

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: 'qtYUwG93SBeu_6S_uK_w3w'

  cache:
    container_name: cache
    image: redis:7-alpine
    restart: on-failure:3
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'

  app:
    container_name: gymentry-app
    image: gymentry:latest
    restart: on-failure:2
    env_file:
      - .env
    ports:
      - '8080:8080'

volumes:
  pg-data:
  redis-data: