name: build-test
on: [pull_request]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: install jdk
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: packaging
        run: ./mvnw -B clean package -DskipTests
  test:
    needs: build
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: install jdk
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: test
        run: ./mvnw test