name: check
on: [push, pull_request]
jobs:
  build:
    runs-on: self-hosted
    container:
      image: alpine:3.14
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: install jdk
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: packaging
        run: ./mvnw -B clean package -DskipTests
  test:
    needs: build
    runs-on: self-hosted
    container:
      image: maven:3.9-eclipse-temurin-21
      env:
        DOCKER_HOST: tcp://host-gateway:2375
        options: --add-host=host-gateway:host-gateway
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: install jdk
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: test
        run: ./mvnw test